from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('farmer/', views.farmer_home, name='farmer'),
    path('gov/', views.gov_home, name='gov'),
    path('', views.landing_page, name='index'),
    path('index', views.landing_page, name='index'),
    path('admins/', views.admin_page, name='admins'),
    path('login/', views.logins, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('far-table/', views.table_view, name='far-table'),
    path('profile/',views.profile_view,name='profile'),
    path('public_profile_view/',views.public_profile_view,name='public_profile_view'),
    path('public_register/', views.public_register, name='public_register'),
    path('product_view/', views.product_view, name='product_view'),
    path('add_pro/', views.product_add, name='add_pro'),
    path('del_pro/<int:id>/',views.product_del,name='del_pro'),
    path('public/', views.public_home, name='public'),
    path('public_pro_view/', views.public_pro_view, name='public_pro_view'),
    path('edit_pro/<int:id>/',views.product_edit,name='edit_pro'),
    path('cart/<int:p_id>/',views.add_to_cart,name='cart'),
    path('cart_view',views.cart_view,name='cart_view'),
    path('cart_del/<int:id>/',views.cart_product_del,name='cart_del'),
    path('payment/<int:id>/',views.payment_dtel,name='payment'),
    path('order_view/',views.farmer_order_view,name='order_view'),
    path('public_order_view/',views.my_order,name='public_order_view'),
    path('order_cancel/<int:id>/',views.my_order_cancel,name='order_cancel'),
    path('alert',views.alert_add,name='alert'),
    path('ad_alert_view',views.admin_alert_view,name='ad_alert_view'),
    path('alert_edit/<int:id>/',views.edit_alert,name='alert_edit'),
    path('alert_del/<int:id>/',views.del_alert,name='alert_del'),
    path('far_alert_view/',views.fa_alert_view,name='far_alert_view'),
    path('gov_add_pro/', views.gov_product_add, name='gov_add_pro'),
    path('gov_view_pro/', views.gov_product_view, name='gov_view_pro'),
    path('gov_edit_pro/<int:id>/', views.gov_pro_edit, name='gov_edit_pro'),
    path('gov_pro_del/<int:id>/',views.del_gov_pro,name='gov_pro_del'),
    path('subsidy_pro',views.far_subsidy_view,name='subsidy_pro'),
    path('farmer_cart/<int:id>/',views.f_add_to_cart,name='farmer_cart'),
    path('far_payment/<int:id>/',views.far_payment_dtel,name='far_payment'),
    path('frmr_pro_view/',views.far_cart_view,name='frmr_pro_view'),
    path('frmr_pro_del/<int:id>/',views.far_cart_product_del,name='frmr_pro_del'),
    path('farmer_order_view/',views.far_order,name='farmer_order_view'),
    path('farmer_order_cancel/<int:id>',views.far_order_cancel,name='farmer_order_cancel'),
    path('gov_order_view/',views.gov_orders,name='gov_order_view'),
    path('notify/',views.notification_add,name='notify'),
    path('gov_notify_view/',views.gov_notification_view,name='gov_notify_view'),
    path('gov_notify_edit/<int:id>',views.edit_notification,name='gov_notify_edit'),
    path('gov_notify_del/<int:id>',views.del_notification,name='gov_notify_del'),
    path('add_address/<int:id>',views.address_add,name='add_address'),
    path('payment/<int:id>/<int:cartid>',views.payment_dtel,name='payment'),
    path('delivery_register/',views.deliver_register,name='delivery_register'),
    path('delivery/',views.deliver_home,name='delivery'),
    path('deliver_profile_view/', views.delivery_profile_view, name='deliver_profile_view'),
    path('fa_notification_view/',views.fa_notification_view,name='fa_notification_view'),
    path('fa_delivery_view/',views.all_delivery_boys,name='fa_delivery_view'),
    path('cancel_del/<int:id>',views.del_cancelled,name='cancel_del'),
    path('avilable_orders/<int:id>',views.ord_avil,name='avilable_orders'),
    path('assignig/<int:id>/<int:cartid>',views.assigning_delivery,name='assignig'),
    path('delivery_request',views.del_reqs,name='delivery_request'),
    path('completed/<int:id>',views.delevery_complete,name='completed'),
    path('far_reject/<int:id>',views.farmer_rejection,name='far_reject'),
    path('far_approve/<int:id>',views.farmer_approve,name='far_approve'),
    path('far_freez/<int:id>',views.farmer_freez,name='far_freez'),
    path('pub-table/',views.public_table,name='pub-table'),
    path('dely-table/',views.delivery_table,name='dely-table'),
    path('product-table/',views.product_table_view,name='product-table'),
    path('all_purchases/',views.purchases_view,name='all_purchases'),
    path('repporting/<int:id>',views.comp_repporting,name='repporting'),
    path('commplaint_view/',views.usr_comp_view,name='commplaint_view'),
    path('all_complains_view/',views.far_comp_view,name='all_complains_view'),
    path('replay/<int:id>',views.far_comp_replay,name='replay'),
    path('gov_far_view/',views.gov_farmer_view,name='gov_far_view'),
    path('gov_far_complaint/<int:id>',views.gov_far_report,name='gov_far_complaint'),
    path('edit_comp/<int:id>',views.editcomp,name='edit_comp'),
    path('del_comp/<int:id>',views.delcomp,name='del_comp'),

    path('sub_purchase_view/',views.sub_purchases_view,name='sub_purchase_view'),
    path('enter_soil_data/', views.enter_soil_data, name='enter_soil_data'),
    path('get_weather', views.get_weather, name='get_weather'),
    path('weather/', views.weather, name='weather'),
    path('upload', views.upload_image, name='upload_image'),



]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)