# Generated by Django 5.1.4 on 2025-01-05 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='login_detl',
            name='email',
        ),
        migrations.RemoveField(
            model_name='login_detl',
            name='password',
        ),
        migrations.AddField(
            model_name='login_detl',
            name='login_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cropapp.login_pass'),
            preserve_default=False,
        ),
    ]
