# Generated by Django 5.1.4 on 2025-04-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
