# Generated by Django 5.1.4 on 2025-01-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0002_login_pass_remove_login_detl_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='login_pass',
            new_name='login',
        ),
        migrations.DeleteModel(
            name='Login_detl',
        ),
    ]
