# Generated by Django 5.1.4 on 2025-04-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='far_address',
            field=models.CharField(max_length=200),
        ),
    ]
