# Generated by Django 5.1.4 on 2025-01-05 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0003_user_rename_login_pass_login_delete_login_detl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cropapp.login'),
        ),
    ]
