# Generated by Django 5.1.4 on 2025-01-09 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0004_user_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='public_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cropapp.login')),
            ],
        ),
    ]
