# Generated by Django 5.1.4 on 2025-04-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0004_alter_user_district_alter_user_far_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.FileField(default=0, upload_to='id_proofs/'),
            preserve_default=False,
        ),
    ]
