# Generated by Django 5.1.4 on 2025-05-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0005_user_id_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.IntegerField(default=0),
        ),
    ]
