# Generated by Django 5.1.6 on 2025-05-01 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0005_user_id_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('farmer_reciever_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_reciever_id', to='cropapp.user')),
                ('farmer_sender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_sender_id', to='cropapp.user')),
                ('public_reciever_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_reciever_id', to='cropapp.public_user')),
                ('public_sender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_sender_id', to='cropapp.public_user')),
            ],
        ),
    ]
