# Generated by Django 5.1.4 on 2025-01-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0005_public_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.CharField(max_length=5)),
            ],
        ),
    ]
