# Generated by Django 5.1.6 on 2025-05-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0006_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chat',
        ),
    ]
