# Generated by Django 5.1.4 on 2025-01-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0006_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
