# Generated by Django 5.1.4 on 2025-05-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0006_user_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_status',
        ),
    ]
