# Generated by Django 5.1.4 on 2025-01-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0007_remove_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
