# Generated by Django 5.1.4 on 2025-01-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0008_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cropapp.login'),
        ),
    ]
