# Generated by Django 5.1.6 on 2025-05-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0007_delete_chat'),
        ('cropapp', '0009_complaint'),
    ]

    operations = [
    ]
