# Generated by Django 5.1.6 on 2025-05-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0010_merge_0007_delete_chat_0009_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='gov_status',
            field=models.IntegerField(default=0),
        ),
    ]
