# Generated by Django 5.1.4 on 2025-01-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0011_alter_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='user_type',
            field=models.CharField(default='farmer', max_length=20),
            preserve_default=False,
        ),
    ]
