# Generated by Django 5.1.4 on 2025-05-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0011_login_gov_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
