# Generated by Django 5.2 on 2025-05-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0012_alter_complaint_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
