# Generated by Django 5.2 on 2025-05-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0013_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
