# Generated by Django 5.1.4 on 2025-02-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0013_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='exp_date',
        ),
    ]
