# Generated by Django 5.2 on 2025-05-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0014_farmer_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='farmer_cart',
            name='quantity',
        ),
    ]
