# Generated by Django 5.1.4 on 2025-02-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0015_payment_exp_month_payment_exp_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='cropapp.login'),
        ),
        migrations.AlterField(
            model_name='public_user',
            name='login_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='us', to='cropapp.login'),
        ),
    ]
