# Generated by Django 5.1.4 on 2025-02-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0016_alter_cart_user_id_alter_public_user_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cancelation_status',
            field=models.IntegerField(default=0),
        ),
    ]
