# Generated by Django 5.1.4 on 2025-02-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0018_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_year',
            field=models.IntegerField(),
        ),
    ]
