# Generated by Django 5.1.4 on 2025-02-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0019_alter_alert_created_at_alter_payment_exp_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
