# Generated by Django 5.1.4 on 2025-02-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0021_alter_alert_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='gov_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.CharField(max_length=10)),
                ('subsidy_price', models.CharField(max_length=10)),
            ],
        ),
    ]
