# Generated by Django 5.1.4 on 2025-02-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0022_gov_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='gov_products',
            name='current_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
