# Generated by Django 5.1.4 on 2025-02-20 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0023_gov_products_current_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.IntegerField(default=0)),
                ('cancelation_status', models.IntegerField(default=0)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cropapp.gov_products')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to='cropapp.login')),
            ],
        ),
    ]
