# Generated by Django 5.1.4 on 2025-02-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0024_farmer_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onwer_name', models.CharField(max_length=25)),
                ('card_no', models.CharField(max_length=15)),
                ('cvv', models.CharField(max_length=5)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('cart_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cropapp.gov_products')),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cropapp.login')),
            ],
        ),
    ]
