# Generated by Django 5.1.4 on 2025-02-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0025_farmer_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_payment',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cropapp.farmer_cart'),
        ),
    ]
