# Generated by Django 5.1.4 on 2025-02-23 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0026_alter_farmer_payment_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='far', to='cropapp.login'),
        ),
    ]
