# Generated by Django 5.1.6 on 2025-03-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0029_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_boy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('far_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_as_table', to='cropapp.login')),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_as_table', to='cropapp.login')),
            ],
        ),
    ]
