# Generated by Django 5.1.4 on 2025-03-29 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0030_delivery_boy'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('cart_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cropapp.cart')),
                ('delivery_team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cropapp.delivery_boy')),
            ],
        ),
    ]
