# Generated by Django 5.1.4 on 2025-04-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0031_delivery_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_status',
            field=models.IntegerField(default=0),
        ),
    ]
